# Generated by Django 4.2 on 2023-04-09 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=100)),
                ('corporate_email', models.BooleanField(default=False)),
                ('user_full_name', models.CharField(blank=True, default='', max_length=100)),
                ('language', models.CharField(choices=[['RO', 'Romanian'], ['EN', 'English'], ['PT', 'Portuguese']], default='python', max_length=100)),
                ('country', models.CharField(choices=[('RO', 'ROMANIA'), ('I', 'IRELAND'), ('PT', 'PORTUGAL')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown event', max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('recurring', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('price', models.IntegerField()),
                ('period', models.CharField(choices=[['WE', 'WEEKLY'], ['MO', 'MONTHLY'], ['YE', 'YEARLY']], max_length=100)),
                ('period_paid', models.IntegerField()),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application.email')),
            ],
        ),
        migrations.CreateModel(
            name='EmailToEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('details', models.CharField(blank=True, max_length=100)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application.email')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application.event')),
            ],
        ),
    ]
