# Generated by Django 4.1.7 on 2023-03-12 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('price', models.IntegerField()),
                ('period', models.CharField(choices=[['WE', 'WEEKLY'], ['MO', 'MONTHLY'], ['YE', 'YEARLY']], max_length=100)),
                ('period_paid', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='email',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='email',
            name='language',
            field=models.CharField(choices=[['RO', 'Romanian'], ['EN', 'English'], ['PT', 'Portuguese']], default='python', max_length=100),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown event', max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateField()),
                ('recurring', models.BooleanField(default=False)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application.email')),
            ],
        ),
    ]
