# Generated by Django 4.1.7 on 2023-03-18 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_event_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='email',
        ),
        migrations.AddField(
            model_name='subscription',
            name='mail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='application.email'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EmailToEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application.email')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application.event')),
            ],
        ),
    ]
