# Generated by Django 4.1.7 on 2023-03-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_remove_event_email_subscription_mail_emailtoevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtoevent',
            name='details',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='emailtoevent',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
